framework:
  webhook:
    routing:
      downloadvideosuccess:
        service: App\Presentation\Webhook\Core\DownloadVideoSuccessRequestParser
        secret: '%env(CORE_TOKEN)%'
      downloadvideofailure:
        service: App\Presentation\Webhook\Core\DownloadVideoFailureRequestParser
        secret: '%env(CORE_TOKEN)%'
      extractsoundsuccess:
        service: App\Presentation\Webhook\Core\ExtractSoundSuccessRequestParser
        secret: '%env(CORE_TOKEN)%'
      extractsoundfailure:
        service: App\Presentation\Webhook\Core\ExtractSoundFailureRequestParser
        secret: '%env(CORE_TOKEN)%'